### PR TITLE
Bump to 0.3.1

### PR DESCRIPTION
**Pull request by RaulPPelaez**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by RaulPPelaez** [comment]
@conda-forge-admin, please rerender

**Comment by RaulPPelaez** [comment]
cc @rusty1s @hadim please review
I removed the pinning of cutlass, seems to build fine with the latest version. I am a bit confused though as to why it is needed as a dependency since it seems to be pulled as a git submodule, but the builds fail without it.

**Comment by hadim** [comment]
Thank you @RaulPPelaez.

Do you want to add yourself as a maintainer?

ALso pytorch is built against CUDA 12.0, and 11.8 (see https://anaconda.org/conda-forge/pytorch-gpu/files?version=2.1.0) - I wonder whether we should also build against 12.0 and 11.8 here. Any idea?

**Comment by RaulPPelaez** [comment]
This is atm a downstream dependency for us, but this is the first time I play around compiling this one. You may add me as a maintainer, I do not mind checking things out when they break if I have the time.
Regarding cuda 11.8 and 12 I would just merge this one and then ask the bot to reopen the migration PRs, I added some missing archs for those so with a little luck they will auto pass.

**Comment by hadim** [comment]
Ok thank you. I added you as a maintainer.

**Review by hadim — COMMENTED** [review]
LGTM. Let's wait for @rusty1s eyes.

**Comment by RaulPPelaez** [comment]
BTW I believe the CUDA 11.8,12 migrations will happen automatically once triton gets them (which is a dep here AFAIK) https://github.com/conda-forge/triton-feedstock/pull/9
I think I fixed that here https://github.com/conda-forge/triton-feedstock/pull/11 but we will have to wait for it to be merged.

**Comment by RaulPPelaez** [comment]
cc @rusty1s could you please review? this will probably make 0.3.1 also build on its own.

**Comment by hadim** [comment]
@RaulPPelaez if you rebase from `main`, I am happy to merge here.

**Pull request merged**
